# extensions/order-selection-extension/shopify-extension.toml

api_version = "2023-10"

[features]
user_defined_action = true

[targets]
admin = [
  "admin.order-index.selection-action.render",
]

[[extensions]]
name = "Order Selection Extension"
handle = "order-selection-extension"
type = "ui_extension"
application_url = "https://your-extension-url.com"  # Replace with your actual extension URL

[[extensions.targeting]]
module = "./src/OrderSelectionExtension.jsx"
target = "admin.order-index.selection-action.render"
